// src/app/shared/components/controls.component.ts
import { Component, input, output } from "@angular/core";

export interface SegmentedOption {
  value: string;
  label: string;
}

/** Interruptor (switch) acessível com rótulo e descrição. */
@Component({
  selector: "app-toggle",
  standalone: true,
  template: `
    <button
      type="button"
      class="toggle"
      role="switch"
      [attr.aria-checked]="checked()"
      (click)="checkedChange.emit(!checked())"
    >
      <span class="toggle__text">
        <span class="toggle__label">{{ label() }}</span>
        @if (description(); as desc) {
          <span class="toggle__desc">{{ desc }}</span>
        }
      </span>
      <span class="toggle__track" [class.is-on]="checked()">
        <span class="toggle__thumb"></span>
      </span>
    </button>
  `,
  styles: `
    .toggle {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      width: 100%;
      padding: 10px 2px;
      border: 0;
      background: transparent;
      font-family: inherit;
      text-align: left;
      cursor: pointer;
    }

    .toggle__text {
      display: flex;
      flex-direction: column;
      gap: 2px;
      min-width: 0;
    }

    .toggle__label {
      font-size: 13.5px;
      font-weight: 600;
      color: var(--nessa-text);
    }

    .toggle__desc {
      font-size: 12.5px;
      line-height: 1.5;
      color: var(--nessa-text-muted);
    }

    .toggle__track {
      position: relative;
      width: 40px;
      height: 22px;
      flex: none;
      border: 1px solid var(--nessa-border);
      border-radius: var(--radius-full);
      background: var(--nessa-surface-2);
      transition: background var(--t-base) var(--ease-out), border-color var(--t-base) var(--ease-out);
    }

    .toggle__track.is-on {
      background: var(--nessa-primary);
      border-color: var(--nessa-primary);
    }

    .toggle__thumb {
      position: absolute;
      top: 2px;
      left: 2px;
      width: 16px;
      height: 16px;
      border-radius: 50%;
      background: var(--nessa-text);
      box-shadow: var(--shadow-xs);
      transition: transform var(--t-base) var(--ease-spring);
    }

    .toggle__track.is-on .toggle__thumb {
      transform: translateX(18px);
    }
  `,
})
export class ToggleComponent {
  readonly checked = input(false);
  readonly label = input.required<string>();
  readonly description = input("");
  readonly checkedChange = output<boolean>();
}

/** Controle segmentado para opções exclusivas. */
@Component({
  selector: "app-segmented",
  standalone: true,
  template: `
    <div class="seg" role="radiogroup" [attr.aria-label]="ariaLabel()">
      @for (option of options(); track option.value) {
        <button
          type="button"
          class="seg__opt"
          role="radio"
          [attr.aria-checked]="option.value === value()"
          (click)="valueChange.emit(option.value)"
        >
          {{ option.label }}
        </button>
      }
    </div>
  `,
  styles: `
    .seg {
      display: inline-flex;
      width: 100%;
      padding: 4px;
      border: 1px solid var(--nessa-border);
      border-radius: var(--radius-sm);
      background: var(--nessa-surface-2);
    }

    .seg__opt {
      flex: 1;
      padding: 7px 12px;
      border: 0;
      border-radius: 6px;
      background: transparent;
      font-family: inherit;
      font-size: 12.5px;
      font-weight: 600;
      color: var(--nessa-text-muted);
      cursor: pointer;
      transition: color var(--t-fast) var(--ease-out), background var(--t-fast) var(--ease-out);
    }

    .seg__opt:hover {
      color: var(--nessa-text);
    }

    .seg__opt[aria-checked="true"] {
      background: var(--nessa-surface-hover);
      color: var(--nessa-text);
      box-shadow: var(--shadow-xs);
    }
  `,
})
export class SegmentedComponent {
  readonly options = input.required<SegmentedOption[]>();
  readonly value = input.required<string>();
  readonly ariaLabel = input("Opções");
  readonly valueChange = output<string>();
}

// src/shared/ui/controls.tsx
/* ============================================================
   NESSA AI — Controles de formulário (shared/ui)
   Base do Reactive Forms da plataforma (Etapa 1: preferências).
   ============================================================ */
import type { InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from "react";
import { cn } from "../../core/utils";

/* ---------- Field (label + erro + hint) ---------- */

interface FieldProps {
  label: string;
  htmlFor?: string;
  hint?: string;
  error?: string | null;
  children: ReactNode;
}

export function Field({ label, htmlFor, hint, error, children }: FieldProps) {
  return (
    <div className="flex flex-col gap-1.5">
      <label htmlFor={htmlFor} className="text-[13px] font-semibold text-[var(--nessa-text)]">
        {label}
      </label>
      {children}
      {error ? (
        <p className="text-[12px] font-medium text-[var(--nessa-danger)]" role="alert">
          {error}
        </p>
      ) : hint ? (
        <p className="text-[12px] text-[var(--nessa-text-muted)]">{hint}</p>
      ) : null}
    </div>
  );
}

/* ---------- TextInput ---------- */

interface TextInputProps extends InputHTMLAttributes<HTMLInputElement> {
  invalid?: boolean;
}

export function TextInput({ invalid = false, className, ...rest }: TextInputProps) {
  return (
    <input
      className={cn(
        "h-10 w-full rounded-[var(--radius-sm)] border bg-[var(--nessa-surface-2)] px-3 text-[13.5px] text-[var(--nessa-text)] shadow-[var(--shadow-inset)] outline-none transition-colors duration-[var(--t-fast)] placeholder:text-[var(--nessa-text-muted)]/70 focus:border-[var(--nessa-accent)]",
        invalid ? "border-[var(--nessa-danger)]" : "border-[var(--nessa-border)]",
        className,
      )}
      {...rest}
    />
  );
}

/* ---------- SelectInput ---------- */

interface SelectInputProps extends SelectHTMLAttributes<HTMLSelectElement> {
  options: Array<{ value: string; label: string }>;
}

export function SelectInput({ options, className, ...rest }: SelectInputProps) {
  return (
    <select
      className={cn(
        "h-10 w-full appearance-none rounded-[var(--radius-sm)] border border-[var(--nessa-border)] bg-[var(--nessa-surface-2)] px-3 text-[13.5px] text-[var(--nessa-text)] shadow-[var(--shadow-inset)] outline-none transition-colors duration-[var(--t-fast)] focus:border-[var(--nessa-accent)]",
        className,
      )}
      {...rest}
    >
      {options.map((option) => (
        <option key={option.value} value={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
}

/* ---------- Toggle ---------- */

interface ToggleProps {
  checked: boolean;
  onChange: (next: boolean) => void;
  label?: string;
  description?: string;
}

export function Toggle({ checked, onChange, label, description }: ToggleProps) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      onClick={() => onChange(!checked)}
      className="group flex w-full items-center justify-between gap-4 rounded-[var(--radius-sm)] px-1 py-1 text-left"
    >
      {(label || description) && (
        <span className="flex flex-col">
          {label && <span className="text-[13px] font-semibold text-[var(--nessa-text)]">{label}</span>}
          {description && <span className="text-[12px] text-[var(--nessa-text-muted)]">{description}</span>}
        </span>
      )}
      <span
        className={cn(
          "relative h-[22px] w-[40px] flex-none rounded-full border transition-colors duration-[var(--t-base)] ease-[var(--ease-out)]",
          checked
            ? "border-[var(--nessa-primary)] bg-[var(--nessa-primary)]"
            : "border-[var(--nessa-border)] bg-[var(--nessa-surface-2)] group-hover:border-[var(--nessa-text-muted)]",
        )}
      >
        <span
          className={cn(
            "absolute top-[2px] left-[2px] h-[16px] w-[16px] rounded-full bg-[var(--nessa-text)] shadow-[var(--shadow-xs)] transition-transform duration-[var(--t-base)] ease-[var(--ease-spring)]",
            checked && "translate-x-[18px]",
          )}
        />
      </span>
    </button>
  );
}

/* ---------- Segmented ---------- */

interface SegmentedProps<T extends string> {
  value: T;
  onChange: (next: T) => void;
  options: Array<{ value: T; label: string }>;
}

export function Segmented<T extends string>({ value, onChange, options }: SegmentedProps<T>) {
  return (
    <div className="inline-flex w-full rounded-[var(--radius-sm)] border border-[var(--nessa-border)] bg-[var(--nessa-surface-2)] p-1 shadow-[var(--shadow-inset)]">
      {options.map((option) => {
        const active = option.value === value;
        return (
          <button
            key={option.value}
            type="button"
            aria-pressed={active}
            onClick={() => onChange(option.value)}
            className={cn(
              "flex-1 rounded-[6px] px-3 py-1.5 text-[12.5px] font-semibold transition-all duration-[var(--t-fast)] ease-[var(--ease-out)]",
              active
                ? "bg-[var(--nessa-surface-hover)] text-[var(--nessa-text)] shadow-[var(--shadow-xs)]"
                : "text-[var(--nessa-text-muted)] hover:text-[var(--nessa-text)]",
            )}
          >
            {option.label}
          </button>
        );
      })}
    </div>
  );
}
